api/urls.py
from django.conf.urls import url, include
from rest_framework.routers import DefaultRouter
from . import views

router = DefaultRouter()
router.register('categories', views.CategoryViewSet)
router.register('articles', views.ArticleViewSet)
router.register('authors', views.AuthorViewSet)


urlpatterns = [
    url(r'^',
        include(router.urls)),
    url(r'^api-auth/',
        include('rest_framework.urls', namespace='rest_framework'))
]

blog/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from . import views

urlpatterns = [
    url(r'^$',
        views.BlogView.as_view(),
        name='blog'),
    url(r'^stats/$',
        views.StatsView.as_view(),
        name='stats'),
    url(r'^about/$',
        views.AboutView.as_view(),
        name='about'),
    url(r'^contact/$',
        views.ContactView.as_view(),
        name='contact'),
    url(r'^authorarticles/(?P<pk>\d+)/$',
        views.AuthorArticlesView.as_view(),
        name='authorarticles'),
    url(r'^categarticles/(?P<pk>\d+)/$',
        views.CategArticlesView.as_view(),
        name='categarticles'),
    url(r'^createarticle/$',
        login_required(views.CreateArticleView.as_view()),
        name='createarticle'),
    url(r'^updatearticle/(?P<pk>\d+)/$',
        login_required(views.UpdateArticleView.as_view()),
        name='updatearticle'),
    url(r'^search/$',
        views.SearchArticlesView.as_view(),
        name='search'),
]

blogger/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import RedirectView

from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    # Examples:
    # url(r'^$', 'blogger.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^$', RedirectView.as_view(url='/blog/', permanent=True),
        name='home'),
    url(r'^blog/', include('blog.urls',
                           namespace='blog',
                           app_name='blog')),
    url(r'accounts/login/$', views.LoginView.as_view(),
        name='login'),
    url(r'accounts/logout/$', views.LogoutView.as_view(permanent=False),
        name='logout'),
    url(r'^api/', include('api.urls')),
    url(r'^admin/', include(admin.site.urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings


class Category(models.Model):
    name = models.CharField(max_length=32)
    descr = models.CharField(max_length=128)

    class Meta:
        verbose_name_plural = 'categories'

    def get_absolute_url(self):
        return '%s/api/categories/%d/' % (settings.SITE_URL, self.id)

    def __unicode__(self):
        return u"%s" % self.name


class Article(models.Model):
    author = models.ForeignKey(User, related_name='articles', editable=False)
    published_on = models.DateTimeField(auto_now_add=True, editable=False)
    categories = models.ManyToManyField(Category,
                                        related_name='articles',
                                        help_text='as many as necessary')
    title = models.CharField(max_length=128,
                             help_text='concise but useful')
    body = models.TextField(help_text='the content')
    tags = models.CharField(max_length=128, blank=True,
                            help_text='space or comma separated')
    IMG_MAX_WIDTH = 256
    IMG_MAX_HEIGHT = 160
    image = models.ImageField(upload_to='articleimg',
                              help_text='optimal size %dx%d pixels' % (
                                            IMG_MAX_WIDTH, IMG_MAX_HEIGHT))
    NUM_ARTICLES_IN_PAGE = 8

    def get_absolute_url(self):
        return '%s/api/articles/%d/' % (settings.SITE_URL, self.id)
 
    def __unicode__(self):
        return u"%s" % self.title

blog/forms.py
import re
from PIL import Image
from django import forms
from django.core.mail import EmailMessage
from django.conf import settings
from django.utils.translation import ugettext_lazy as _
from .models import Article


class ContactForm(forms.Form):
    required_css_class = 'required'

    name = forms.CharField(required=True, max_length=64)
    email_address = forms.EmailField(required=True, max_length=128)
    message = forms.CharField(required=True, widget=forms.Textarea)

    def send_msg(self):
        from_email = self.cleaned_data['email_address']
        email = EmailMessage(subject='Msg from Blog',
                             cc=[from_email, ],
                             body=self.cleaned_data['message'],
                             to=[settings.EMAIL_HOST_USER, ],
                             headers={'Reply-To': from_email})
        email.send()


class ArticleForm(forms.ModelForm):
    required_css_class = 'required'

    class Meta:
        model = Article
        fields = ['title', 'body', 'categories', 'tags', 'image']

    # def clean_tags(self):
    #     return " ".join(set(re.findall(r"[\w'-]+",
    #                                    self.cleaned_data['tags']))).lower()

    def clean_image(self):
        imgdata = self.cleaned_data.get('image')
        # if it's there it's valid
        if imgdata:
            if imgdata.size > settings.MAX_UPLOAD_SIZE:
                raise forms.ValidationError(
                        _('The image file size must be under %(max_size)d bytes. Current file size is %(cur_size)d bytes.'),
                        code='invalid',
                        params={'max_size': settings.MAX_UPLOAD_SIZE,
                                'cur_size': imgdata.size })
        return imgdata

    def clean(self):
        super(ArticleForm, self).clean()
        tags = re.findall(r"[\w'-]+", self.cleaned_data['tags'])
        categs = self.cleaned_data.get('categories')
        # if the categs are valid (i.e. at least one selected)
        if categs:
            categs = [c.name.lower() for c in categs]
            # add the selected categs to the tags and remove duplicates
            newtags = set(tags+categs)
            # rejoin the tags and add a space on both ends to enable
            # exact searching of tags
            self.cleaned_data['tags'] = " "+" ".join(newtags)+" "

    def save(self, *args, **kwargs):
        article = super(ArticleForm, self).save(*args, **kwargs)
        if 'image' in self.changed_data:
            im = Image.open(article.image.path)
            im.thumbnail((Article.IMG_MAX_WIDTH,
                          Article.IMG_MAX_HEIGHT,), Image.ANTIALIAS)
            im.save(article.image.path)
        return article

blog/views.py
import re
from django.core.urlresolvers import reverse_lazy
from django.views.generic import ListView, \
        TemplateView, FormView, CreateView, UpdateView
from django.views.generic.detail import SingleObjectMixin
from django.db.models import Q, Count
from django.contrib.auth.models import User
from . import forms
from .models import Category, Article


class CategoriesMixin(object):

    def get_context_data(self, **kwargs):
        context = super(CategoriesMixin, self).get_context_data(**kwargs)
        context['categories'] = Category.objects.all().order_by('name')
        return context


class BlogView(CategoriesMixin, ListView):
    # model = Article
    queryset = Article.objects.order_by('-published_on')
    template_name = "blog/blog.html"
    paginate_by = Article.NUM_ARTICLES_IN_PAGE


class AuthorArticlesView(CategoriesMixin, SingleObjectMixin, ListView):
    # model = Article
    template_name = "blog/authorarticles.html"
    paginate_by = Article.NUM_ARTICLES_IN_PAGE

    def get(self, request, *args, **kwargs):
        self.object = self.get_object(queryset=User.objects.all())
        return super(AuthorArticlesView, self).get(request, *args, **kwargs)

    def get_queryset(self):
        return self.object.articles.order_by('-published_on')

    # no need to override get_context_data, since self.object
    # is available to the template! (as object)
    # def get_context_data(self, **kwargs):
    #     context = super(AuthorArticlesView, self).get_context_data(**kwargs)
    #     context['author'] = self.object
    #     return context


class CategArticlesView(CategoriesMixin, SingleObjectMixin, ListView):
    # model = Article
    template_name = "blog/categarticles.html"
    paginate_by = Article.NUM_ARTICLES_IN_PAGE

    def get(self, request, *args, **kwargs):
        self.object = self.get_object(queryset=Category.objects.all())
        return super(CategArticlesView, self).get(request, *args, **kwargs)

    def get_queryset(self):
        return self.object.articles.order_by('-published_on')


class SearchArticlesView(CategoriesMixin, ListView):
    # model = Article
    #template_name = "blog/searcharticles.html"
    template_name = "blog/blog.html"
    paginate_by = Article.NUM_ARTICLES_IN_PAGE

    def get_queryset(self):
        oritags = re.findall(r"[\w'-]+",
                             self.request.GET.get(u'search', "").lower())
        # get rid of duplicates
        searchtags = set(oritags)
        queryargs = [Q(tags__contains=" "+i+" ") for i in searchtags]
        return Article.objects.filter(*queryargs).order_by('-published_on')


class StatsView(CategoriesMixin, TemplateView):
    template_name = "blog/stats.html"

    def get_context_data(self, **kwargs):
        context = super(StatsView, self).get_context_data(**kwargs)
        context['stats4authors'] = User.objects. \
                                   annotate(numarticles=Count('articles')). \
                                   order_by('-numarticles')[:10]
        context['stats4categories'] = Category.objects. \
                                      annotate(
                                            numarticles=Count('articles')). \
                                      order_by('-numarticles')[:10]
        return context


class AboutView(CategoriesMixin, TemplateView):
    template_name = "blog/about.html"


class ContactView(FormView):
    form_class = forms.ContactForm
    template_name = "blog/contact.html"
    success_url = reverse_lazy("blog:blog")

    def form_valid(self, form):
        form.send_msg()
        return super(ContactView, self).form_valid(form)


class CreateArticleView(CategoriesMixin, CreateView):
    form_class = forms.ArticleForm
    template_name = "blog/create_updatearticle.html"
    success_url = reverse_lazy("blog:blog")

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super(CreateArticleView, self).form_valid(form)


class UpdateArticleView(CategoriesMixin, UpdateView):
    model = Article
    form_class = forms.ArticleForm
    template_name = "blog/create_updatearticle.html"
    success_url = reverse_lazy("blog:blog")

blog/templates/blog/about.html
{% extends "base.html" %}
{% block nav_about %}class="active"{% endblock %}
{% block mainbar %}
	<div class="article">
		<h2>What this blog is about</h2>
		<div class="clr"></div>
		<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.
		</p>
	</div>
	<div class="article">
		<h2>Who we are</h2>
		<div class="clr"></div>
		<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.
		</p>
	</div>
{% endblock %}

blog/templates/blog/articles.html
{% for article in object_list %}
	<div class="article">
		<h2>{{ article.title }}</h2>
		<div class="clr"></div>
		<p>Posted by <a href="{% url 'blog:authorarticles' pk=article.author.id %}">{{ article.author.first_name }}&nbsp{{ article.author.last_name }}</a>
		 on {{ article.published_on }}
		</p>
		<img src="{{ article.image.url }}" width="256" height="160" alt="" class="fl">
		<p>{{ article.body|truncatewords:100 }}</p>
		<p>
		 <a href="#" class="obg"><strong>Read more</strong></a>
	       	 <span>&nbsp;&bull;&nbsp;</span>
		 <a href="#" class="obg"><strong>Comments (N)</strong></a>
		 {% if article.author == request.user %}
		  <span>&nbsp;&bull;&nbsp;</span>
		  <a href="{% url 'blog:updatearticle' pk=article.id %}"><strong>Edit</strong></a>
		 {% endif %}
		</p>
		<p>
		 Categories:
		 {% for categ in article.categories.all %}
		 <a href="{% url 'blog:categarticles' pk=categ.id %}">{{ categ|capfirst }}</a>
		 {% endfor %}
		 <span>&nbsp;&bull;&nbsp;</span>
		 Tags: {{ article.tags }}
		</p>
		<div class="clr"></div>
		<div class="clr"></div>
	</div>
{% endfor %}
{% if page_obj.paginator.num_pages > 1 %}
<div class="pagination">
Archive: 
 {% if page_obj.has_previous %}
  <a href="?page=1" class="page">latest</a>
  <a href="?page={{ page_obj.previous_page_number }}" class="page">younger</a>
 {% endif %}
 {% if page_obj.has_next %}
  <a href="?page={{ page_obj.next_page_number }}" class="page">older</a>
  <a href="?page={{ page_obj.paginator.num_pages }}" class="page">oldest</a>
 {% endif %}
</div>
{% endif %}

blog/templates/blog/authorarticles.html
{% extends "base.html" %}
{% block nav_blog %}class="active"{% endblock %}
{% block mainbar %}
<div class="article">
	<h2>Articles posted by {{ object.first_name }}&nbsp{{ object.last_name }}</h2>
	<p>Username: <strong>{{ object.username }}</strong></p>
	<p>email: <strong><a href="mailto:{{ object.email }}?subject=A%20message">{{ object.email }}</a></strong></p>
	<p>Joined on: <strong>{{ object.date_joined }}</strong></p>
</div>
<div class="clr"></div>
{% include "blog/articles.html" %}
{% endblock %}

blog/templates/blog/blog.html
{% extends "base.html" %}
{% block nav_blog %}class="active"{% endblock %}
{% block mainbar %}
{% include "blog/articles.html" %}
{% endblock %}

blog/templates/blog/categarticles.html
{% extends "base.html" %}
{% block nav_blog %}class="active"{% endblock %}
{% block mainbar %}
<div class="article">
	<h2>{{ object.name|capfirst }}</h2>
	<p>{{ object.descr }}</p>
</div>
<div class="clr"></div>
{% include "blog/articles.html" %}
{% endblock %}

blog/templates/blog/contact.html
{% extends "base.html" %}
{% load staticfiles %}
{% block nav_contact %}class="active"{% endblock %}
{% block mainbar %}
	<div class="article">
		<h2>Your input is most welcome</h2>
		<div class="clr"></div>
		<ol>
		<form action='' method='POST'>
			{% csrf_token %}
			{{ form.as_ul }}
			<li>
			<input type="image" name="imageField" id="imageField" src="{% static "images/submit.gif" %}" class="send" />
			</li>
		</form>
		</ol>
	</div>
{% endblock %}

blog/templates/blog/create_updatearticle.html
{% extends "base.html" %}
{% load staticfiles %}
{% block mainbar %}
	<div class="article">
		<h2>
		 {% if object %}
		 	Update article
		 {% else %}
		 	Create a new article
		 {% endif %}
		</h2>
		<div class="clr"></div>
		<ol>
		<form enctype="multipart/form-data" method='POST' action=''>
			{% csrf_token %}
			{{ form.as_ul }}
			<li>
			<input type="image" name="imageField" id="imageField" src="{% static "images/submit.gif" %}" class="send" />
			</li>
		</form>
		</ol>
	</div>
{% endblock %}

blog/templates/blog/createarticle.html
{% extends "base.html" %}
{% load staticfiles %}
{% block mainbar %}
	<div class="article">
		<h2>Create a new article</h2>
		<div class="clr"></div>
		<ol>
		<form enctype="multipart/form-data" method='POST' action=''>
			{% csrf_token %}
			{{ form.as_ul }}
			<li>
			<input type="image" name="imageField" id="imageField" src="{% static "images/submit.gif" %}" class="send" />
			</li>
		</form>
		</ol>
	</div>
{% endblock %}

blog/templates/blog/stats.html
{% extends "base.html" %}
{% block nav_stats %}class="active"{% endblock %}
{% block mainbar %}
	<div class="article">
		<h2>Most active bloggers</h2>
		<table>
		 <tr>
		  <th>Author</th>
		  <th>Articles</th>
		 </tr>
		 {% for stat in stats4authors %}
		  <tr>
		   <td>{{ stat.first_name }} {{ stat.last_name }}</td>
		   <td>{{ stat.numarticles }}</td>
		  </tr>
		 {% endfor %}
		</table>
		<div class="clr"></div>
	</div>
	<div class="article">
		<h2>Most active categories</h2>
		<table>
		 <tr>
		  <th>Category</th>
		  <th>Articles</th>
		 </tr>
		 {% for stat in stats4categories %}
		  <tr>
		   <td>{{ stat.name }}</td>
		   <td>{{ stat.numarticles }}</td>
		  </tr>
		 {% endfor %}
		</table>
	<div class="clr"></div>
	</div>
{% endblock %}

blog/templates/blog/support.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>ClearFocus | Support</title>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<link href="style.css" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="js/cufon-yui.js"></script>
<script type="text/javascript" src="js/arial.js"></script>
<script type="text/javascript" src="js/cuf_run.js"></script>
</head>
<body>
<div class="main">
  <div class="header">
    <div class="header_resize">
      <div class="logo">
        <h1><a href="index.html"><span>Clear</span>Focus <small>Put your slogan here</small></a></h1>
      </div>
      <div class="clr"></div>
      <div class="menu_nav">
        <ul>
          <li><a href="index.html">Home</a></li>
          <li class="active"><a href="support.html">Support</a></li>
          <li><a href="about.html">About Us</a></li>
          <li><a href="blog.html">Blog</a></li>
          <li><a href="contact.html">Contact Us</a></li>
        </ul>
      </div>
      <div class="searchform">
        <form id="formsearch" name="formsearch" method="post" action="#">
          <input name="button_search" src="images/search_btn.gif" class="button_search" type="image" />
          <span>
          <input name="editbox_search" class="editbox_search" id="editbox_search" maxlength="80" value="Search" type="text" />
          </span>
          <div class="clr"></div>
        </form>
      </div>
    </div>
  </div>
  <div class="content">
    <div class="content_resize">
      <div class="mainbar">
        <div class="article">
          <h2><span>Support to</span> Company Name</h2>
          <div class="clr"></div>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. <strong>Suspendisse nulla ligula, blandit ultricies aliquet ac, lobortis in massa. Nunc dolor sem, tincidunt vitae viverra in, egestas sed lacus.</strong> Etiam in ullamcorper felis. Nulla cursus feugiat leo, ut dictum metus semper a. Vivamus euismod, arcu gravida sollicitudin vestibulum, quam sem tempus quam, quis ullamcorper erat nunc in massa. Donec aliquet ante non diam sollicitudin quis auctor velit sodales. Morbi neque est, posuere at fringilla non, mollis nec nibh. Sed commodo tortor nec sem tincidunt mattis. Nam convallis aliquam nibh eu luctus. Nunc vel tincidunt lacus. Suspendisse sit amet pulvinar ante.</p>
          <p>Phasellus diam justo, laoreet vel vulputate eu, congue vel est. Maecenas eros libero, sollicitudin a vulputate fermentum, ultrices vel lacus. Nam in metus non augue fermentum consequat ultrices ac enim. Integer aliquam urna non diam aliquam eget hendrerit sem molestie.</p>
          <p><strong>Lorem ipsum dolor sit amet</strong></p>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum eget bibendum tellus. Nunc vel imperdiet tellus. Mauris ornare aliquam urna, accumsan bibendum eros auctor ac.</p>
          <ul class="sb_menu">
            <li><a href="#"><strong>Lorem ipsum</strong></a></li>
            <li><a href="#"><strong>Lorem ipsum</strong></a></li>
            <li><a href="#"><strong>Lorem ipsum</strong></a></li>
            <li><a href="#"><strong>Lorem ipsum</strong></a></li>
            <li><a href="#"><strong>Lorem ipsum</strong></a></li>
            <li><a href="#"><strong>Lorem ipsum</strong></a></li>
          </ul>
        </div>
      </div>
      <div class="sidebar">
        <div class="gadget">
          <h2 class="star"><span>Sidebar</span> Menu</h2>
          <div class="clr"></div>
          <ul class="sb_menu">
            <li><a href="#">Home</a></li>
            <li><a href="#">TemplateInfo</a></li>
            <li><a href="#">Style Demo</a></li>
            <li><a href="#">Blog</a></li>
            <li><a href="#">Archives</a></li>
            <li><a href="#">Website Templates</a></li>
          </ul>
        </div>
        <div class="gadget">
          <h2 class="star"><span>Sponsors</span></h2>
          <div class="clr"></div>
          <ul class="ex_menu">
            <li><a href="#">DreamTemplate</a><br />
              Over 6,000+ Premium Web Templates</li>
            <li><a href="#">TemplateSOLD</a><br />
              Premium WordPress &amp; Joomla Themes</li>
            <li><a href="#">ImHosted.com</a><br />
              Affordable Web Hosting Provider</li>
            <li><a href="#">DreamStock</a><br />
              Download Amazing Stock Photos</li>
            <li><a href="#">Evrsoft</a><br />
              Website Builder Software &amp; Tools</li>
            <li><a href="#">MyVectorStore</a><br />
              Royalty Free Stock Icons</li>
          </ul>
        </div>
      </div>
      <div class="clr"></div>
    </div>
  </div>
  <div class="fbg">
    <div class="fbg_resize">
      <div class="col c1">
        <h2><span>Image Gallery</span></h2>
        <a href="#"><img src="images/pic1.jpg" width="56" height="56" alt="" /></a> <a href="#"><img src="images/pic2.jpg" width="56" height="56" alt="" /></a> <a href="#"><img src="images/pic3.jpg" width="56" height="56" alt="" /></a> <a href="#"><img src="images/pic4.jpg" width="56" height="56" alt="" /></a> <a href="#"><img src="images/pic5.jpg" width="56" height="56" alt="" /></a> <a href="#"><img src="images/pic6.jpg" width="56" height="56" alt="" /></a> </div>
      <div class="col c2">
        <h2><span>Lorem Ipsum</span></h2>
        <p>Lorem ipsum dolor<br />
          Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec libero. Suspendisse bibendum. Cras id urna. <a href="#">Morbi tincidunt, orci ac convallis aliquam</a>, lectus turpis varius lorem, eu posuere nunc justo tempus leo. Donec mattis, purus nec placerat bibendum, dui pede condimentum odio, ac blandit ante orci ut diam.</p>
      </div>
      <div class="col c3">
        <h2><span>About</span></h2>
        <img src="images/white.jpg" width="56" height="56" alt="" />
        <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec libero. Suspendisse bibendum. Cras id urna. Morbi tincidunt, orci ac convallis aliquam, lectus turpis varius lorem, eu posuere nunc justo tempus leo. llorem, eu posuere nunc justo tempus leo. Donec mattis, purus nec placerat bibendum. <a href="#">Learn more...</a></p>
      </div>
      <div class="clr"></div>
    </div>
  </div>
  <div class="footer">
    <div class="footer_resize">
      <p class="lf">&copy; Copyright MyWebSite. Designed by Blue <a href="http://www.bluewebtemplates.com/">Website Templates</a></p>
      <ul class="fmenu">
        <li><a href="index.html">Home</a></li>
        <li class="active"><a href="support.html">Support</a></li>
        <li><a href="blog.html">Blog</a></li>
        <li><a href="about.html">About Us</a></li>
        <li><a href="contact.html">Contacts</a></li>
      </ul>
      <div class="clr"></div>
    </div>
  </div>
</div>
<div align=center>This template  downloaded form <a href='http://all-free-download.com/free-website-templates/'>free website templates</a></div></body>
</html>