api/urls.py
from django.conf.urls import url, include
from rest_framework.routers import DefaultRouter
from . import views

router = DefaultRouter()
router.register('categories', views.CategoryViewSet)
router.register('articles', views.ArticleViewSet)
router.register('authors', views.AuthorViewSet)


urlpatterns = [
    url(r'^',
        include(router.urls)),
    url(r'^api-auth/',
        include('rest_framework.urls', namespace='rest_framework'))
]

blog/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from . import views

urlpatterns = [
    url(r'^$',
        views.BlogView.as_view(),
        name='blog'),
    url(r'^stats/$',
        views.StatsView.as_view(),
        name='stats'),
    url(r'^about/$',
        views.AboutView.as_view(),
        name='about'),
    url(r'^contact/$',
        views.ContactView.as_view(),
        name='contact'),
    url(r'^authorarticles/(?P<pk>\d+)/$',
        views.AuthorArticlesView.as_view(),
        name='authorarticles'),
    url(r'^categarticles/(?P<pk>\d+)/$',
        views.CategArticlesView.as_view(),
        name='categarticles'),
    url(r'^createarticle/$',
        login_required(views.CreateArticleView.as_view()),
        name='createarticle'),
    url(r'^updatearticle/(?P<pk>\d+)/$',
        login_required(views.UpdateArticleView.as_view()),
        name='updatearticle'),
    url(r'^search/$',
        views.SearchArticlesView.as_view(),
        name='search'),
]

blogger/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import RedirectView

from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    # Examples:
    # url(r'^$', 'blogger.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^$', RedirectView.as_view(url='/blog/', permanent=True),
        name='home'),
    url(r'^blog/', include('blog.urls',
                           namespace='blog',
                           app_name='blog')),
    url(r'accounts/login/$', views.LoginView.as_view(),
        name='login'),
    url(r'accounts/logout/$', views.LogoutView.as_view(permanent=False),
        name='logout'),
    url(r'^api/', include('api.urls')),
    url(r'^admin/', include(admin.site.urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load staticfiles %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>FatalistiSiNasce</title>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<link href="{% static "style.css" %}" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="{% static "js/cufon-yui.js" %}"></script>
<script type="text/javascript" src="{% static "js/arial.js" %}"></script>
<script type="text/javascript" src="{% static "js/cuf_run.js" %}"></script>
</head>
<body>
<div class="main">
  <div class="header">
    <div class="header_resize">
      <div class="logo">
	      <h1><a href="{% url 'home' %}"><span>Fatalisti</span> si nasce <small>esperienze di vita vissuta</small></a></h1>
      </div>
      <div class="clr"></div>
      <div class="menu_nav">
       <ul>
	<li {% block nav_blog %}{% endblock %}><a href="{% url 'blog:blog' %}">Blog</a></li>
	<li {% block nav_stats %}{% endblock %}><a href="{% url 'blog:stats' %}">Stats</a></li>
	<li {% block nav_about %}{% endblock %}><a href="{% url 'blog:about' %}">About</a></li>
	<li {% block nav_contact %}{% endblock %}><a href="{% url 'blog:contact' %}">Contact</a></li>
       </ul>
      </div>
      <div class="searchform">
	      <form id="formsearch" name="formsearch" method="GET" action="{% url 'blog:search' %}">
	  <input name="button_search" src="{% static "images/search_btn.gif" %}" class="button_search" type="image" />
          <span>
          <input name="search" class="editbox_search" id="id_search" maxlength="80" value="" type="text" />
          </span>
          <div class="clr"></div>
       </form>
      </div>
    </div>
  </div>
  <div class="content">
    <div class="content_resize">
      <div class="mainbar">
      {% block mainbar %}{% endblock %}
      </div>
      <div class="sidebar">
      {% block sidebar %}
       <div class="gadget">
	<h2 class="star"><span><cufon class="cufon cufon-canvas" alt="Staff menu" style="width: 90px; height: 24px;"><canvas width="138" height="34" style="width: 138px; height: 34px; top: -5px; left: -15px;"></canvas><cufontext>Staff menu</cufontext></cufon></span></h2>
	<div class="clr"></div>
	<ul class="sb_menu">
	 {% if request.user.is_authenticated %}
	  <li>
	   <a href="{% url 'blog:createarticle' %}">New article</a>
	  </li>
	  <li>
	   <a href="{% url 'blog:authorarticles' pk=request.user.id %}">My articles</a>
	  </li>
	  <li>
	   <a href="{% url 'logout' %}">Logout <strong>{{ request.user.get_username }}</strong></a>
	  </li>
	 {% else %}
	  <li>
	   <a href="{% url 'login' %}">Login</a>
	  </li>
	 {% endif %}
  	</ul>
       </div>
      {% if categories %}
       <div class="gadget">
	<h2 class="star"><span><cufon class="cufon cufon-canvas" alt="Categories" style="width: 90px; height: 24px;"><canvas width="138" height="34" style="width: 138px; height: 34px; top: -5px; left: -15px;"></canvas><cufontext>Categories</cufontext></cufon></span></h2>
	<div class="clr"></div>
	<ul class="sb_menu">
	 {% for categ in categories %}
	  <li>
	   <a href="{% url 'blog:categarticles' pk=categ.id %}">{{ categ|capfirst }}</a>
	  </li>
	 {% endfor %}
  	</ul>
       </div>
      {% endif %}
     {% endblock %}
     </div>
     <div class="clr"></div>
    </div>
  </div>
  <div class="fbg">
    <div class="fbg_resize">
      <div class="col c1">
        <h2><span>Image Gallery</span></h2>
	<a href="#"><img src="{% static "images/pic1.jpg" %}" width="56" height="56" alt="" /></a>
	<a href="#"><img src="{% static "images/pic2.jpg" %}" width="56" height="56" alt="" /></a>
	<a href="#"><img src="{% static "images/pic3.jpg" %}" width="56" height="56" alt="" /></a>
	<a href="#"><img src="{% static "images/pic4.jpg" %}" width="56" height="56" alt="" /></a>
	<a href="#"><img src="{% static "images/pic5.jpg" %}" width="56" height="56" alt="" /></a>
	<a href="#"><img src="{% static "images/pic6.jpg" %}" width="56" height="56" alt="" /></a> </div>
      <div class="col c2">
        <h2><span>Lorem Ipsum</span></h2>
        <p>Lorem ipsum dolor<br />
          Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec libero. Suspendisse bibendum. Cras id urna. <a href="#">Morbi tincidunt, orci ac convallis aliquam</a>, lectus turpis varius lorem, eu posuere nunc justo tempus leo. Donec mattis, purus nec placerat bibendum, dui pede condimentum odio, ac blandit ante orci ut diam.</p>
      </div>
      <div class="col c3">
        <h2><span>About</span></h2>
	<img src="{% static "images/white.jpg" %}" width="56" height="56" alt="" />
        <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec libero. Suspendisse bibendum. Cras id urna. Morbi tincidunt, orci ac convallis aliquam, lectus turpis varius lorem, eu posuere nunc justo tempus leo. llorem, eu posuere nunc justo tempus leo. Donec mattis, purus nec placerat bibendum. <a href="#">Learn more...</a></p>
      </div>
      <div class="clr"></div>
    </div>
  </div>
  <div class="footer">
    <div class="footer_resize">
      <p class="lf">&copy; Copyright MyWebSite. Designed by Blue <a href="http://www.bluewebtemplates.com/">Website Templates</a></p>
      <ul class="fmenu">
        <li class="active"><a href="index.html">Home</a></li>
        <li><a href="support.html">Support</a></li>
        <li><a href="blog.html">Blog</a></li>
        <li><a href="about.html">About Us</a></li>
        <li><a href="contact.html">Contacts</a></li>
      </ul>
      <div class="clr"></div>
    </div>
  </div>
</div>
<div align=center>This template  downloaded form <a href='http://all-free-download.com/free-website-templates/'>free website templates</a></div></body>
</html>